// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diag} from '../models';
import {backend} from '../models';

export function CancelGather():Promise<void>;

export function GetTraceSettings():Promise<diag.TraceSettings>;

export function IsElevated():Promise<boolean>;

export function IsTracingActive():Promise<boolean>;

export function PickGatherDestination():Promise<string>;

export function RequestElevation():Promise<void>;

export function SetDevToolsState(arg1:boolean):Promise<void>;

export function SetLaunchMode(arg1:boolean):Promise<void>;

export function StartTracing(arg1:backend.TraceStartOptions):Promise<void>;

export function StopTracing():Promise<void>;

export function StopTracingAndGather(arg1:string):Promise<void>;

export function ToggleDevTools():Promise<void>;
