// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGather() {
  return window['go']['backend']['App']['CancelGather']();
}

export function GetTraceSettings() {
  return window['go']['backend']['App']['GetTraceSettings']();
}

export function IsElevated() {
  return window['go']['backend']['App']['IsElevated']();
}

export function IsTracingActive() {
  return window['go']['backend']['App']['IsTracingActive']();
}

export function PickGatherDestination() {
  return window['go']['backend']['App']['PickGatherDestination']();
}

export function RequestElevation() {
  return window['go']['backend']['App']['RequestElevation']();
}

export function SetDevToolsState(arg1) {
  return window['go']['backend']['App']['SetDevToolsState'](arg1);
}

export function SetLaunchMode(arg1) {
  return window['go']['backend']['App']['SetLaunchMode'](arg1);
}

export function StartTracing(arg1) {
  return window['go']['backend']['App']['StartTracing'](arg1);
}

export function StopTracing() {
  return window['go']['backend']['App']['StopTracing']();
}

export function StopTracingAndGather(arg1) {
  return window['go']['backend']['App']['StopTracingAndGather'](arg1);
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools']();
}
